#10: Info page content
andersnylund/simple-budget-app pull request #55
Opened 2018-11-15 10:55 UTC by tu-tran

Fixes #10

2018-11-15 17:58 UTC, andersnylund reviewed
I would still like to have screenshots from different banks and how to export your data from there. I'm not sure yet how that would be done the best way.

I also found a "bug" where the page is wider than the AppBar:
<img width="1679" alt="screenshot 2018-11-15 at 13 37 35" src="https://user-images.githubusercontent.com/18005239/48571699-3dc6fe00-e910-11e8-95e0-a69138afd12b.png">
so if you scroll all the way to the right, there is a white space left to the AppBar

2018-11-15 18:00 UTC, tu-tran commented on src/components/InfoSteps.js
>    },
Hmm, unfortunately Google gave me nothing, and I am not a customer of both those banks... Do you have a screenshot there ?

2018-11-15 18:02 UTC, tu-tran commented on src/components/InfoSteps.js
>    },
> I would still want that we wouldn't use material-ui's way of styling with class based styling. Instead I would like to have it purely done with styled-components. But that is only my preference

Eew, in my experience, not following theme unit is a pain later on to support multiple themes (but not sure if its the case fore web dev though)... Anyway, for this kind of project, I think either way is fine so did not really think twice about this

2018-11-15 18:42 UTC, andersnylund commented on src/components/InfoSteps.js
>    },
> Eew, in my experience, not following theme unit is a pain later on to support multiple themes (but not sure if its the case for web dev though)... Anyway, for this kind of project, I think either way is fine so did not really think twice about this

Could use the Context API for that 😏 But let's go with this for now. I just find the styled-components so much more readable

2018-11-15 18:44 UTC, andersnylund commented
Didn't even think about it, but now I realized that having screenshots on the info page is not that great of an idea. If we need to change anything, we will have to update the screenshots each time

2018-11-15 18:46 UTC, tu-tran commented
> Didn't even think about it, but now I realized that having screenshots on the info page is not that great of an idea. If we need to change anything, we will have to update the screenshots each time

yeah :D I was trying to do the "interactive guide" , where I could pop the arrow and show preview of real React component. Unfortunately, my dummy web skill get stuck after a few days :( So I went with the quick and dirty solution :(

2018-11-16 16:15 UTC, andersnylund approved these changes

2018-11-16 19:11 UTC, andersnylund requested changes
Changing my mind

2018-11-19 17:00 UTC, andersnylund approved these changes

2018-11-19 17:03 UTC, merged